name: ota
on:
  workflow_dispatch:
  push:
    branches:
      - 'jt/merge-ota' # XX next/arvo
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "make an OTA update to arvo on ~wannec-dozzod-marzod (devstream)"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/ota
        with:
          ship: 'devstream'
          credentials: ${{ secrets.JANEWAY_SERVICE_KEY }}
          ssh-sec-key: ${{ secrets.JANEWAY_SSH_SEC_KEY }}
          ssh-pub-key: ${{ secrets.JANEWAY_SSH_PUB_KEY }}
          ref: 'next/arvo'
